### ISSUE TITLE
Home Assistant configuration contains invalid name

### ISSUE THREAD

**Issue by robin13** [xoseperez/espurna#1183]
espurna has a limit on hostname that a hostname cannot contain and underscore `_` (but does allow a minus (`-`)), while home assistant has a limit that an entity may only contain alphanumeric plus underscore for the name.

If you name your espurna device e.g. `sonoff-th16-01` this will result in a configuration:

```
switch:
  - name: sonoff-th16-01               <-- invalid (a)
    platform: mqtt
...

sensor:
  - name: sonoff-th16-01 temperature   <-- invalid (b)
```

(a) is invalid because it has `-` used, and (b) is invalid because there are both `-` and spaces (` `) used.
It would be good to check (I think around [here](https://github.com/xoseperez/espurna/blob/dd12251e43174281c737ca0868d5e6fcb8711558/code/espurna/homeassistant.ino#L172)) if the resulting name is valid by home assistant entity standards (ascii alphanumeric + underscore) and fix if necessary.
