### ISSUE TITLE
show config topic field blank when code uploaded from platformio

### ISSUE THREAD

**Issue by nilava** [xoseperez/espurna#1762]
The show config in HASS is not working properly when i am uploading code from platform io instead of using the prebuilt firmware for nodemcu lolin.

```
switch:
  - name: ESPURNA_1F7B48
    platform: mqtt
    state_topic: 
    command_topic: 
    payload_on: 1
    payload_off: 0
    availability_topic: 
    payload_available: 1
    payload_not_available: 0
 ```

This is what i am getting where as you can see state_topic, command_topic and availability_topic is blank
