### ISSUE TITLE
Xiaomi Desklamp Rotary Encoder Bugs

### ISSUE THREAD

**Issue by fluffymadness** [xoseperez/espurna#1934]
There are some weird issues with my xiaomi desklamp
I upgraded to the latest nightly that is linked via github
and the rotary encoder behavior is completely broken
when i try to dim down in dims down a bit and is then full brightness again
same with color change
when i turn the wheel to the right it changes between yellow and white gradually
worked fine on older builds
newest tasmota with the xiaomi desklamp module has the same issue for me

(espurna-1.13.6-dev.nightly20191001+gitbd385f9f-xiaomi-smart-desk-lamp) broken
https://github.com/xoseperez/espurna/issues/1621#issuecomment-471177403 -> works fine

**Comment by mcspr** [comment]
Thanks for the report! I do see the issue here:
https://github.com/xoseperez/espurna/blob/bd385f9fbc71bff007f8b9fe5825777b3bf03dce/code/espurna/light.ino#L939

When step is negative and brightness already approaches 0, lightBrightness function receives negative value. Due to signed / unsigned conversion, resulting brightness is converted from -1 to some value near 4294967295 and in the end into the 100% that you are seeing
I can't see any issues with the encoder handling, but will re-check in the morning and commit the fix.

**Comment by fluffymadness** [comment]
thanks for the quick reply. Another thing I've noticed, is it maybe possible to expose color temperature via mqtt ? The pregenerated homeassistant template from espurna only gives me brightness control.

```
light:
  - name: ESPURNA_83D22DF2
    state_topic: 
    command_topic: 
    payload_on: 1
    payload_off: 0
    availability_topic: 
    payload_available: 
    payload_not_available: 
    brightness_state_topic: 
    brightness_command_topic: 
```
