### ISSUE TITLE
Home Assistant switch setup does not work with JSON payload via MQTT

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#219]
Originally reported by: **Erwin (Bitbucket: [elonden](https://bitbucket.org/elonden), GitHub: [elonden](https://github.com/elonden))**

----------------------------------------

Been breaking my head around this for a while but it seems I'm between a rock and hard place.

When using the MQTT setup with JSON payload activated the HA switch button only works one time and then it stops. It seems the relay topic which HA looks for is also sent in json format which seems not to be picked up by HA.

When I disable the json payload the switch works fine and I see the mqtt message for the relay/0 topic being published.

The setup is fairly easy in HA:

```
#!yaml

switch:
 - platform: mqtt
    name: "SW115"
    state_topic: "home/switch/sw115/relay/0"
    command_topic: "home/switch/sw115/relay/0/set"
    payload_on: 1
    payload_off: 0
    optimistic: false
    qos: 0
    retain: true
```
 
When the json payload is off I can see the relay message being published:

```
#!text

home/switch/sw115/relay/0 1
home/switch/sw115/relay/0 0
home/switch/sw115/relay/0 1
home/switch/sw115/relay/0 1
home/switch/sw115/relay/0 0

```

The issue I then have is that the sensor values of the Sonoff POW are no longer being transmitted and thus renders that feature useless in HA.

It would be nice to have the relay status always being sent in mqtt format so HA can track for that and the other information in json format to be able to obtain that data out of the Sonoff POW.

I pulled the code yesterday so the issue is prevalent on 1.9.4b
