### ISSUE TITLE
MQTT: Brightness calculation is currently wrong in master-branch (and probably dev as well)

### ISSUE THREAD

**Issue by Skaronator** [xoseperez/espurna#755]
Something is wrong with the brightness calculation. I can reproduce this 100% in Home Assistant via MQTT.

1. Turn Light on in HA and set color to Red (for example)
2. Change brighness to something else (100% -> 25%)
3. Click on **the same*** color and you see that the brighness actually change (which shouldn't be the case)
\* You don't have to select the same color but it is easier to see the brighness difference.

My HA Config:
```
light:
  - name: H801_200
    platform: mqtt
    state_topic: H801-200/relay/0
    command_topic: H801-200/relay/0/set
    payload_on: 1
    payload_off: 0
    availability_topic: H801-200/status
    payload_available: 1
    payload_not_available: 0
    brightness_state_topic: H801-200/brightness
    brightness_command_topic: H801-200/brightness/set
    rgb_state_topic: H801-200/rgb
    rgb_command_topic: H801-200/rgb/set
    color_temp_state_topic: H801-200/mired
    color_temp_command_topic: H801-200/mired/set   
```
