### ISSUE TITLE
Hiding the help hint text on web  interface 

### ISSUE THREAD

**Issue by zafrirron** [xoseperez/espurna#773]
It may be useful to others... 
small jquery function I use to hide  the help text on the espurna web pages by creating small "hint" button that shows the hint help text and creating a "close" button to hide it
adding the js function to custom.js and calling it from $(function() (at the bottom of custom.js), adding the css part to custom.css will do the magic.

 It not perfect, since its relying on original page structure (were .hint css class used) to be modified on page load but do the work on most pages and clean the hint text we all know by hart ;-)

(just don't forget to "gulp" your frontend in case you deciding to try this @ home...)

@xoseperez - may decide to add something similar (and better) to the core.. 

Javascript Part
```javascript
function loadPageScripts() {
    $(".hint").hide();
    $(".hint").before("<div class='hint-button hint-open' onclick='$(this).next().next().show();$(this).hide();$(this).next().show(1000);' >Hint&gt;&gt;&gt;</div> ");
    $(".hint").after(" <div class='hint-button hint-close' onclick='$(this).prev().hide(1000);$(this).hide();$(this).prev().prev().show();'>&lt;&lt;&lt;Hide</div>");
    $(".hint").next().hide();
}
```
CSS part
```css
.hint-button {
    font-size: small;
    letter-spacing: 0;
    margin: 0 5px;
    padding: 3px;
    border: 1px dashed #ccc;
    border-radius: 3px;
    height: 12px;
    line-height: 1.1em;
    cursor: help;
}
.hint-open {
    float: left;
}
.hint-close {
    float:right;
}
```
